export enum AppStatusCode {
	// --- General Auth ---
	ACCESS_TOKEN_MISSING = 'ACCESS_TOKEN_MISSING',
	ACCESS_TOKEN_EXPIRED = 'ACCESS_TOKEN_EXPIRED',
	ACCESS_TOKEN_INVALID = 'ACCESS_TOKEN_INVALID',
	REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',

	SOCIAL_LOGIN_REQUIRED = 'SOCIAL_LOGIN_REQUIRED',

	// --- Signup / Verification ---
	SIGNUP_TOKEN_INVALID = 'SIGNUP_TOKEN_INVALID',
	SIGNUP_TOKEN_EXPIRED = 'SIGNUP_TOKEN_EXPIRED',
	SIGNUP_TOKEN_ALREADY_USED = 'SIGNUP_TOKEN_ALREADY_USED',
	USER_NOT_FOUND = 'USER_NOT_FOUND',
	EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',
	VERIFICATION_FAILED = 'VERIFICATION_FAILED',
	EMAIL_VERIFICATION_SEND_FAILED = 'EMAIL_VERIFICATION_SEND_FAILED',
	EMAIL_PASSWORD_RESET_SEND_FAILED = 'EMAIL_PASSWORD_RESET_SEND_FAILED',
	PASSWORD_RESET_FAILED = 'PASSWORD_RESET_FAILED',

	// --- Login / Session ---
	INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
	SESSION_INVALID_OR_EXPIRED = 'SESSION_INVALID_OR_EXPIRED',

	// --- Terms ---
	TERMS_ACCEPTANCE_REQUIRED = 'TERMS_ACCEPTANCE_REQUIRED',

	// --- 2FA Setup / Verification ---
	TWO_FA_RECOVERY_TOKEN_INVALID = 'TWO_FA_RECOVERY_TOKEN_INVALID',
	TWO_FA_RECOVERY_TOKEN_EXPIRED = 'TWO_FA_RECOVERY_TOKEN_EXPIRED',
	TWO_FA_RECOVERY_TOKEN_ALREADY_USED = 'TWO_FA_RECOVERY_TOKEN_ALREADY_USED',

	TWO_FA_SETUP_SUCCESS = 'TWO_FA_SETUP_SUCCESS',
	TWO_FA_VERIFICATION_NOT_PENDING = 'TWO_FA_VERIFICATION_NOT_PENDING',
	TWO_FA_VERIFICATION_FAILED = 'TWO_FA_VERIFICATION_FAILED',
	TWO_FA_RECOVERY_NOT_INITIATED = 'TWO_FA_RECOVERY_NOT_INITIATED',
	TWO_FA_VERIFICATION_REQUIRED = 'TWO_FA_VERIFICATION_REQUIRED',
	TWO_FA_NOT_CONFIGURED = 'TWO_FA_NOT_CONFIGURED',
	TWO_FA_VERIFICATION_CODE_INVALID = 'TWO_FA_VERIFICATION_CODE_INVALID',
	TWO_FA_SETUP_INVALID = 'TWO_FA_SETUP_INVALID',
	EMAIL_TWO_FA_RECOVERY_SEND_FAILED = 'EMAIL_TWO_FA_RECOVERY_SEND_FAILED',
	TWO_FA_RECOVERY_FAILED = 'TWO_FA_RECOVERY_FAILED',
	// --- Password Reset ---
	PASSWORD_RESET_NOT_INITIATED = 'PASSWORD_RESET_NOT_INITIATED',

	PASSWORD_RESET_TOKEN_INVALID = 'PASSWORD_RESET_TOKEN_INVALID',
	PASSWORD_RESET_TOKEN_EXPIRED = 'PASSWORD_RESET_TOKEN_EXPIRED',
	PASSWORD_RESET_TOKEN_ALREADY_USED = 'PASSWORD_RESET_TOKEN_ALREADY_USED',

	// --- CSRF ---
	CSRF_TOKEN_INVALID = 'CSRF_TOKEN_INVALID',

	// --- Errors ---
	INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
	TERMS_ALREADY_ACCEPTED = 'TERMS_ALREADY_ACCEPTED',

	// --- Emails ---
	CONFIRMATION_EMAIL_SENT_IF_NEEDED = 'CONFIRMATION_EMAIL_SENT_IF_NEEDED',
}

/**
 * @swagger
 * components:
 *   schemas:
 *     StatusCode:
 *       type: string
 *       description: >
 *         Application-level status codes used to represent the outcome of various operations,
 *         including errors, success signals, and conditions requiring user interaction.
 *         These codes are designed for programmatic handling by frontend or client logic.
 *       enum:
 *         - ACCESS_TOKEN_MISSING
 *         - ACCESS_TOKEN_EXPIRED
 *         - ACCESS_TOKEN_INVALID
 *         - REFRESH_TOKEN_INVALID
 *         - SOCIAL_LOGIN_REQUIRED
 *         - SIGNUP_TOKEN_INVALID
 *         - SIGNUP_TOKEN_EXPIRED
 *         - SIGNUP_TOKEN_ALREADY_USED
 *         - USER_NOT_FOUND
 *         - EMAIL_ALREADY_IN_USE
 *         - VERIFICATION_FAILED
 *         - EMAIL_VERIFICATION_SEND_FAILED
 *         - EMAIL_PASSWORD_RESET_SEND_FAILED
 *         - PASSWORD_RESET_FAILED
 *         - INVALID_CREDENTIALS
 *         - SESSION_INVALID_OR_EXPIRED
 *         - TERMS_ACCEPTANCE_REQUIRED
 *         - TWO_FA_RECOVERY_TOKEN_INVALID
 *         - TWO_FA_RECOVERY_TOKEN_EXPIRED
 *         - TWO_FA_RECOVERY_TOKEN_ALREADY_USED
 *         - TWO_FA_SETUP_SUCCESS
 *         - TWO_FA_VERIFICATION_NOT_PENDING
 *         - TWO_FA_VERIFICATION_FAILED
 *         - TWO_FA_RECOVERY_NOT_INITIATED
 *         - TWO_FA_VERIFICATION_REQUIRED
 *         - TWO_FA_NOT_CONFIGURED
 *         - TWO_FA_VERIFICATION_CODE_INVALID
 *         - TWO_FA_SETUP_INVALID
 *         - EMAIL_TWO_FA_RECOVERY_SEND_FAILED
 *         - TWO_FA_RECOVERY_FAILED
 *         - PASSWORD_RESET_NOT_INITIATED
 *         - PASSWORD_RESET_TOKEN_INVALID
 *         - PASSWORD_RESET_TOKEN_EXPIRED
 *         - PASSWORD_RESET_TOKEN_ALREADY_USED
 *         - CSRF_TOKEN_INVALID
 *         - INTERNAL_SERVER_ERROR
 *         - TERMS_ALREADY_ACCEPTED
 *         - CONFIRMATION_EMAIL_SENT_IF_NEEDED
 */
