services:
  postgres:
    container_name: local-postgress
    image: postgres:13.16-bookworm
    environment:
      POSTGRES_USER: admin_pg
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flexible_leaves
    ports:
      - "5433:5432"
  
  redis:
    container_name: local-redis
    image: redis:6.0.18-alpine
    ports:
      - "6379:6379"