services:
    postgres:
        container_name: local-postgress
        image: postgres:13.16-bookworm
        environment:
            POSTGRES_USER: admin_pg
            POSTGRES_PASSWORD: password
            POSTGRES_DB: local-express-hybrid-auth-api-db
        ports:
            - '5433:5432'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U admin_pg -d local-express-hybrid-auth-api-db']
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 10s

    redis:
        container_name: local-redis
        image: redis:6.0.18-alpine
        ports:
            - '6379:6379'

    migrate:
        build:
            context: ../
            dockerfile: Dockerfile
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            - DATABASE_URL=postgresql://admin_pg:password@postgres:5432/local-express-hybrid-auth-api-db
            - NODE_ENV=development
        command: >
            sh -c "
              echo 'PostgreSQL is healthy, running migrations...'
              npx prisma migrate reset --force
            "
        restart: 'no'

    smtp4dev:
        container_name: local-smtp4dev
        image: rnwood/smtp4dev
        ports:
            - '5000:80' # Web UI
            - '2525:2525' # SMTP server
        restart: unless-stopped
        environment:
            - Logging__LogLevel__Default=Information
