services:
  postgres:
    container_name: local-postgress
    image: postgres:13.16-bookworm
    environment:
      POSTGRES_USER: admin_pg
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flexible_leaves
    ports:
      - "5433:5432"
  
  redis:
    container_name: local-redis
    image: redis:6.0.18-alpine
    ports:
      - "6379:6379"

  smtp4dev:
    container_name: local-smtp4dev
    image: rnwood/smtp4dev
    ports:
      - "5000:80"   # Web UI
      - "2525:25"   # SMTP server
    restart: unless-stopped
    environment:
      - Logging__LogLevel__Default=Information