
### Valid token

POST http://localhost:3001/auth/verify-signup
content-type: application/json

{
    "token": "signup-valid-2"
}


### Used token

POST http://localhost:3001/auth/verify-signup
content-type: application/json

{
    "token": "signup-used-2"
}


### Expired token

POST http://localhost:3001/auth/verify-signup
content-type: application/json

{
    "token": "signup-expired-2"
}

### Not found token

POST http://localhost:3001/auth/verify-signup
content-type: application/json

{
    "token": "signup-not-found"
}

